#goal definition
#object ID to look for
string object_id
#where to look for the object in terms of pan/tilt looking direction
float32 ptu_pan
float32 ptu_tilt
---
#result definition
int32 found
---
#feedback
string status
