sensor_msgs/PointCloud2 cloud
std_msgs/String scene_name
std_msgs/String view_name
#geometry_msgs/Transform transform #transform to world coordinate system
#float32[] translation
#float32[] quaternion
float32[] transform
std_msgs/Time timestamp
---
std_msgs/String[] ids
geometry_msgs/Transform[] transforms
