sensor_msgs/PointCloud2 cloud
float32[] transform #optional transform to world coordinate system
std_msgs/String scene_name #optional name for multiview recognition
std_msgs/String view_name #optional name for multiview recognition
---
std_msgs/String[] ids
geometry_msgs/Transform[] transforms

#ratio of visible points
float32[] confidence

# centroid of the cluster
geometry_msgs/Point32[] centroid

# bounding box of the cluster
object_perception_msgs/BBox[] bbox

# point cloud of the model transformed into camera coordinates
sensor_msgs/PointCloud2[] models_cloud
